name: Build and Test Docker Image

on:
  push:
    branches:
      - devconatiner
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t troute -f docker/Dockerfile.troute .

      - name: Run LowerColorado Test
        continue-on-error: true
        run: docker/troute.sh -V3 -f test/LowerColorado_TX/test_AnA.yaml

      - name: Run pytests
        continue-on-error: true
        run: docker run troute:latest pytest